// Generated by CoffeeScript 1.3.3
(function() {
  var Pie, assert;

  assert = require('assert');

  Pie = require('../../models/pie');

  describe('Pie', function() {
    return describe('create', function() {
      var pie;
      pie = null;
      before(function() {
        return pie = new Pie({
          name: 'Key Lime'
        });
      });
      it("sets name", function() {
        return assert.equal(pie.name, 'Key Lime');
      });
      it("defaults to some state", function() {
        return assert.equal(pie.state, 'inactive');
      });
      return it("generates Id", function() {
        return assert.equal(pie.id, 'Key-Lime');
      });
    });
  });

}).call(this);
