// Generated by CoffeeScript 1.3.3
(function() {
  var Pie, redis;

  redis = require('redis').createClient();

  Pie = (function() {

    Pie.key = function() {
      return "Pie:" + Process.env.NODE_ENV;
    };

    function Pie(attributes) {
      var key, value;
      for (key in attributes) {
        value = attributes[key];
        this[key] = value;
      }
      this.setDefaults();
      this;

    }

    Pie.prototype.setDefaults = function() {
      if (!this.state) {
        this.state = 'inactive';
      }
      return this.generateId();
    };

    Pie.prototype.generateId = function() {
      if (!this.id && this.name) {
        return this.id = this.name.replace(/\s/g, '-');
      }
    };

    Pie.prototype.save = function(callback) {
      var _this = this;
      this.generateId();
      return redis.hset(Pie.key(), this.id, JSON.stringify(this), function(err, code) {
        return callback(null, _this);
      });
    };

    return Pie;

  })();

  module.exports = Pie;

}).call(this);
